### ISSUE TITLE
Error message should use same words from where its caused

### ISSUE THREAD

**Issue by xpmuyanja** [flexion/msab-arts-locator#181]
Type
 (select up to three that apply) 
 - Error message reads “Between one and three categories are required”
       - Recommendation: error message should be consistent with the cause of the error
           - System should bounce to where the error is found for user to easily 
![Type-error msg](https://user-images.githubusercontent.com/86261039/122812484-59989a80-d297-11eb-9733-b8a1e21d10ad.png)
find and fix it.

**Comment by bdruth** [comment]
Related to work on https://github.com/flexion/msab-arts-locator/issues/171

**Comment by bdruth** [comment]
@xpmuyanja - We can easily change the message to more accurately refer to the Art Location "types" instead of categories. That's a good catch, we didn't notice that the form was referring to that differently.

Unfortunately, we don't have a good way of introducing a UX that would scroll to that area in the form right now. The way that error messages (including validation errors), is such that they display at the bottom of the form, near the `Submit` button, as you know. If we scroll to that part of the form, the user won't see the error message, unless we also delay before we scroll, which won't be a great UX. Ideally, the validation errors would appear in the form itself, as well, but the current UX doesn't support that and we'd probably want to create a new story to overhaul how form validation errors work for this.

Any concerns with just fixing the text and deferring any more overhaul to a future story?

**Comment by xpmuyanja** [comment]
Error message caused by selecting many Art Types - fixed. (the message now- Between one and three art location type identifiers are required. 
![Type-error msg](https://user-images.githubusercontent.com/86261039/122999619-1ceea100-d374-11eb-8d71-cbe13ac6faad.png)

**Comment by xpmuyanja** [comment]
Fixed - error message uses the same words as the cause of the error itself
![Error Msg-Art_Type](https://user-images.githubusercontent.com/86261039/122999982-8cfd2700-d374-11eb-9eb6-b7b855952e6f.png)

**Comment by bdruth** [comment]
Great, thanks for retesting @xpmuyanja!
