### ISSUE TITLE
Bugs list

### ISSUE THREAD

**Issue by christophersbarrett** [flexion/msab-arts-locator#73]
<s>Checkboxes UI not updating when checked
<s> Optional fields in location form need to be either not included when empty, or perhaps undefined? Dynamo doesn't like empty strings.

**Comment by christophersbarrett** [comment]
<s>not getting body, or text from the response from lambdas.-

**Comment by christophersbarrett** [comment]
<s>Need to replace hardcoded urls in front end code with a baseURL value

**Comment by uxforgood** [comment]
- [x] Add favicon to site (emailed you files) - **priority low**



- [x] Location tags should display entire tag name (ex., VISUAL ARTS, FOLK/TRADITIONAL, etc) **priority high**

- [x] Display tag names in all caps letters (ex., VISUAL ARTS, FOLK/TRADITIONAL, etc) **priority high**

- [x] Location tags in the Submit Location form should be ordered alphabetically **priority medium**

- [x] After I click on "Map" and am taken to the map app on my phone, the location is displaying with lat/long coordinates instead of the actual address. User will need to see the actual address within the map application. **priority high**

- [x] After search results display, reduce the white space between the search bar and results by half (too much white space) **priority medium**

- [x] Left align tags with the other items in the search result card (title, pic) and decrease space between tags by half **priority medium**

- [x] In search results, add comma after city and then a single space before appending the ZIP **priority high**

- [x] Purple heading bar has too much space at the top above the logos. Should be the same as the bottom margin under the logos **priority medium**

- [x] Increase font size of the listing address and description by 1-2 points **priority medium**

- [x] Move the thumbnail image down so it top aligns with the address, increase thumbnail size to  **priority medium**

- [x] Add helper text to form **priority high**

- [x] Reduce bottom margin of footer **priority low**

- [x] Reduce size of instructional text on submit form ("Fill out...etc") **priority high**

- [x] Remove state from submit location form **priority medium**

**Comment by christophersbarrett** [comment]
<s> Update city search to be case insensitive

**Comment by christophersbarrett** [comment]
<s>Add terms of use check box, and text

**Comment by christophersbarrett** [comment]
<s> Add logic to standardize city name on retention, as well as on text city search

**Comment by christophersbarrett** [comment]
<s> Make sure image is limited to 1mb size

**Comment by christophersbarrett** [comment]
<s >make sure to only display approved locations

**Comment by uxforgood** [comment]
## Filter bugs
- [x] On category tag instructions (white text in gray box), the text should be font weight 600 and add left padding of 15px to text - NK
- [x] When filtered, the tags should display the entire tag name
- [x] When filtered, the delete icon should have left margin of 10px and have #A9AEB1 background color - NK

## Submit location form
- [x] Add text to image upload to read: "(optional - max size 1 MB)" - NK

**Comment by christophersbarrett** [comment]
Add text for users using Internet Explorer that the site is best viewed with any other browser.

**Comment by christophersbarrett** [comment]
<s> Finalize Email text and ToS text.

**Comment by uxforgood** [comment]
# All remaining bugs

## High
- [x] In submit location form, user must include 1 type (CB)
- [x] Update text in all 4 email templates - include all hard returns as shown in the Word file (attached to this story) (NK)
[E-mail messages_final.docx](https://github.com/flexion/msab-arts-locator/files/3355406/E-mail.messages_final.docx)
- [x] When filtering by category, the search results aren't showing the mile distance (CB)
- [x] Enter final TOS text into app (NK)
- [x] Change search field label to "Find Arts in Minnesota" (NK)

## Low
- [x] Add logic to standardize city name on retention, as well as on text city search (CB)
- [x] Search results are in the reverse order - closest should be at the top (CB)
- [x] In submit location form, flip the placement of the captcha and TOS checkbox - checkbox should come first (NK)
- [x] In submit location form, add space in "filetypes" for image upload (NK)
- [x] In submit location form, the "I agree to terms of service" font should be ASAP font family (NK)
